Taltech added
dat5-06/zap pull request #84
Opened 2024-12-04 13:20 UTC by Maxnm47

![dogofwisdom](https://github.com/user-attachments/assets/a0f4a944-0015-4374-a303-33358a2b03b3)
![60340027](https://github.com/user-attachments/assets/f319dc65-1a90-4282-b46d-e2c20f5164db)
![snip3](https://github.com/user-attachments/assets/92ac92d4-7f97-4482-af9e-1c32c9dffa85)
![hanz](https://github.com/user-attachments/assets/63bbe5dd-73c3-465c-9842-dc3592c93113)

2024-12-04 13:34 UTC, askeko requested changes
I think the comments to this pull request breaks some GDPR laws

2024-12-04 14:23 UTC, Maxnm47 commented
> I think the comments to this pull request breaks some GDPR laws

no

2024-12-04 21:17 UTC, Tinggaard commented on core/notebooks/00/caltech_CNN_LSTM/00_CNN_LSTM_caltech.ipynb
And clear output - it looks very scuffed :)

2024-12-04 21:19 UTC, Tinggaard commented on core/preprocessing/acn.py
> +    # Write the output to a CSV file, dont know if works but wont test 30 min no no.
what

2024-12-04 21:20 UTC, Tinggaard commented on core/util/get_caltech.py
> +    parks = [get_caltech_dataset(features)]
There is no need for this to be a list, right?

2024-12-04 21:21 UTC, Tinggaard commented
![yes](https://github.com/user-attachments/assets/a0f4a944-0015-4374-a303-33358a2b03b3)

2024-12-05 08:50 UTC, Tinggaard commented
@Maxnm47 jeg fikser det, no worries

2024-12-05 08:52 UTC, Tinggaard approved these changes

2024-12-05 08:55 UTC, merged